version: '3.7'

services:
  dotnet:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: dotnet.Dockerfile
    image: dotnet
    ports:
      - 80:80
      - 443:443
    deploy:
      resources:
        limits:
          memory: 30M
        reservations:
          memory: 15M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s
  java:
    depends_on:
      - redis
    image: java
    build:
      context: .
      dockerfile: java.Dockerfile
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 15M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s
  redis:
    image: redis:alpine
#not used yet
volumes:
  app_data: {}
